### ISSUE TITLE
Font in Safari

### ISSUE THREAD

**Issue by Bad-Science** [aosdict/yacs#73]
The open sans font is not working in safari. A default font is rendered instead.

**Comment by aosdict** [comment]
Also of note: font does not get bolded anywhere in Chrome. I have tested with more standard fonts which do get bolded. Something is probably wrong with how we're including Open Sans, I guess?

**Comment by gonsie** [comment]
It looks like you are just downloading the 300 weight of Open Sans (at yacs/vendor/assets/stylesheets/open_sans_300.css). You should also download 700 weight font. You might also need use `font-weight: 700;` instead of the `font-weight: bold;` attribute to get everything to work correctly.

Also, it looks like you are trying to use Open Sans weight 100 [here](https://github.com/aosdict/yacs/blob/master/app/assets/stylesheets/index.css.erb#L73). Again, you haven't actually downloaded this weight.

**Comment by aosdict** [comment]
This appears to be working now in my very old version of Safari so I believe it is fixed.
